name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Verifica o repositorio do Git 
        uses: actions/checkout@v2

      - name: Instala o node com a versão
        uses: actions/setup-node@v1
        with:
          node-version: 14


      - name: configura o lint
        run: npm install

      - name: executa o lint para verificar
        run: npx eslint .
        # run: eslint --no-inline-config --ext .js --no-error-on-unmatched-pattern -c .eslintrc.json .
  # evaluator:
  #   name: Evaluator
  #   needs: [run-linters]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: evaluator 
  #       run: echo "tudo certo"